/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlythuvienptit.ui;

import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.event.ActionListener;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlythuvienptit.controllers.ChiTietPMListener;
import quanlythuvienptit.database.dao.DocGiaDAO;
import quanlythuvienptit.database.dao.LopDAO;
import quanlythuvienptit.database.dao.NganhHocDAO;
import quanlythuvienptit.database.dao.NhaXuatBanDAO;
import quanlythuvienptit.database.dao.PhieuMuonTraDAO;
import quanlythuvienptit.database.dao.Phieu_TLDAO;
import quanlythuvienptit.database.dao.TacGiaDAO;
import quanlythuvienptit.database.dao.TaiLieuDAO;
import quanlythuvienptit.database.dao.UserDAO;

/**
 *
 * @author Admin
 */
public class JF_PhieuMuon extends javax.swing.JFrame {

    /**
     * Creates new form JF_PhieuMuon
     */
    public JF_PhieuMuon() {
        initComponents();
        this.addAction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        phieumuon = new javax.swing.JLabel();
        maDG = new javax.swing.JLabel();
        tenDG = new javax.swing.JLabel();
        lop = new javax.swing.JLabel();
        chuyenNganh = new javax.swing.JLabel();
        ngayMuon = new javax.swing.JLabel();
        ngaytra = new javax.swing.JLabel();
        maPhieu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dstailieu = new javax.swing.JTable();
        capNhat = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        xuatPhieu = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        phieumuon.setBackground(new java.awt.Color(255, 102, 102));
        phieumuon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        phieumuon.setForeground(new java.awt.Color(255, 255, 255));
        phieumuon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phieumuon.setText("PHIẾU MƯỢN TÀI LIỆU");
        phieumuon.setOpaque(true);

        maDG.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maDG.setText("Mã Độc Giả");

        tenDG.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tenDG.setText("Tên Độc Giả");

        lop.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lop.setText("Lớp Hành Chính");

        chuyenNganh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chuyenNganh.setText("Chuyên Ngành");

        ngayMuon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ngayMuon.setText("Ngày Mượn");

        ngaytra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ngaytra.setText("Ngày Phải Trả");

        maPhieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maPhieu.setText("Mã Phiếu");

        dstailieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dstailieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tài Liệu", "Tên Tài Liệu", "NXB", "Tác Giả", "Trạng Thái"
            }
        ));
        dstailieu.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane1.setViewportView(dstailieu);

        capNhat.setBackground(new java.awt.Color(153, 255, 255));
        capNhat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        capNhat.setText("Cập nhật phiếu");

        xoa.setBackground(new java.awt.Color(153, 255, 255));
        xoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xoa.setText("Xóa");

        xuatPhieu.setBackground(new java.awt.Color(153, 255, 255));
        xuatPhieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        xuatPhieu.setText("Xuất Phiếu");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Kiểu Mượn");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Người Tạo Phiếu");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tại chỗ", "Mượn về" }));

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Edit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maDG)
                    .addComponent(tenDG)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(lop)
                        .addComponent(chuyenNganh)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngayMuon)
                            .addComponent(maPhieu)
                            .addComponent(jLabel9)
                            .addComponent(ngaytra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(30, 30, 30)
                .addComponent(capNhat)
                .addGap(29, 29, 29)
                .addComponent(xoa)
                .addGap(44, 44, 44)
                .addComponent(xuatPhieu)
                .addGap(38, 38, 38))
            .addComponent(phieumuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(phieumuon, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maDG)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tenDG)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lop)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chuyenNganh)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maPhieu)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngayMuon))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngaytra)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xuatPhieu)
                    .addComponent(xoa)
                    .addComponent(capNhat)
                    .addComponent(jButton2))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void addAction(){
        ActionListener ac = new ChiTietPMListener(this);
        this.capNhat.addActionListener(ac);
        this.jButton2.addActionListener(ac);
        this.xoa.addActionListener(ac);
        this.xuatPhieu.addActionListener(ac);
    }
    
    public void dislay(String id) throws SQLException{
        ResultSet rs = PhieuMuonTraDAO.getChiTietPhieu(id);
        if(rs.next()){
            this.jTextField1.setText(rs.getString("MaDG"));
            this.jTextField1.setEditable(false);
            
            this.jTextField8.setText(rs.getString("ID_MuonTra"));
            this.jTextField8.setEditable(false);
            
            this.jComboBox1.setSelectedItem(rs.getString("KieuMuon"));
            this.jComboBox1.setEnabled(false);
            
            this.jDateChooser1.setDate(rs.getDate("NgayMuon"));
            this.jDateChooser1.setEnabled(false);
            
            this.jDateChooser2.setDate(rs.getDate("HanTra"));
            this.jDateChooser2.setEnabled(false);
            
            this.jTextField2.setText(DocGiaDAO.getTenDG(rs.getString("MaDG")));
            this.jTextField2.setEditable(false);
            
            this.jTextField5.setText(rs.getString("NguoiChoMuon"));
            this.jTextField5.setEditable(false);
            
            this.jTextField3.setText(LopDAO.searchTenLop(DocGiaDAO.searchMaLop(rs.getString("MaDG"))));
            this.jTextField3.setEditable(false);
            
            this.jTextField4.setText(NganhHocDAO.searchTenNganh(DocGiaDAO.searchMaNganh(rs.getString("MaDG"))));
            this.jTextField4.setEditable(false);
            
            ArrayList<String> dsMaTL = Phieu_TLDAO.getMaTL(rs.getString("ID_MuonTra"));
            DefaultTableModel model = (DefaultTableModel)this.dstailieu.getModel();
            for(String maTL : dsMaTL){
                String[] row = new String[5];
                row[0] = maTL;
                row[1] = TaiLieuDAO.searchTenTL(maTL);
                row[2] = NhaXuatBanDAO.searchTenNXB(TaiLieuDAO.searchMaNXB(maTL));
                row[3] = TacGiaDAO.searchTenTG(TaiLieuDAO.searchMaTG(maTL));
                row[4] = Phieu_TLDAO.getTrangThaiMuonTra(rs.getString("ID_MuonTra"), maTL);
                model.addRow(row);
            }
            this.dstailieu.setModel(model);
            this.dstailieu.setEnabled(false);
            
            this.capNhat.setVisible(false);
            this.xoa.setVisible(false);
        } 
    }
    
    public void update(){
        String maDG = this.jTextField1.getText();
        String tenDG = this.jTextField2.getText();
        DocGiaDAO.updatetenDG(maDG, tenDG);
        
        String tenLop = this.jTextField3.getText();
        String maLop = DocGiaDAO.searchMaLop(maDG);
        LopDAO.updateTenLop(maLop, tenLop);
        
        String tenNganh = this.jTextField4.getText();
        String maNganh = DocGiaDAO.searchMaNganh(maDG);
        NganhHocDAO.updateTenNganh(maNganh, tenNganh);
        
        String maPhieu = this.jTextField8.getText();
        String NguoiTao = this.jTextField5.getText();
        PhieuMuonTraDAO.updateNguoiChoMuon(maPhieu, NguoiTao);
        
        String kieuMuon = (String)this.jComboBox1.getSelectedItem();
        PhieuMuonTraDAO.updateKieuMuon(maPhieu, kieuMuon);
        
        Date date = jDateChooser2.getDate(); 
        String hanTra = "";
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        hanTra = dateFormat.format(date);
        PhieuMuonTraDAO.updateHanTra(maPhieu, hanTra);
        
        JOptionPane.showMessageDialog(null, "Đã cập nhật", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void delete(){
        try{
            String maPhieu = this.jTextField8.getText();
            Phieu_TLDAO.delete(maPhieu);
            PhieuMuonTraDAO.deletePhieu(maPhieu);
            JOptionPane.showMessageDialog(null, "Đã xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi!!!", "Lỗiii", JOptionPane.ERROR_MESSAGE);
        }
    }
    public void createPDF() {
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream("phieumuon.pdf"));
            document.open();

            String fontPath = "C:/Windows/Fonts/times.ttf";
            BaseFont baseFont = BaseFont.createFont(fontPath, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            Font vietnameseFont = new Font(baseFont, 12, Font.NORMAL);

            Paragraph title = new Paragraph("PHIẾU MƯỢN TÀI LIỆU", new Font(baseFont, 16, Font.BOLD));
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            PdfPTable table1 = new PdfPTable(2);
            table1.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
            table1.setSpacingBefore(10);
            table1.setSpacingAfter(20);
            table1.setWidthPercentage(100);

            table1.addCell(new Phrase("Mã độc giả: " + jTextField1.getText(), vietnameseFont));
            table1.addCell(new Phrase("Mã Phiếu: " + jTextField8.getText(), vietnameseFont));
            table1.addCell(new Phrase("Tên độc giả: " + jTextField2.getText(), vietnameseFont));
            table1.addCell(new Phrase("Kiểu mượn: " + jComboBox1.getSelectedItem(), vietnameseFont));
            table1.addCell(new Phrase("Lớp hành chính: " + jTextField3.getText(), vietnameseFont));
            Date date1 = jDateChooser1.getDate();
            String ngayMuon = "";
            SimpleDateFormat dateFormat1 = new SimpleDateFormat("dd/MM/yyyy");
            ngayMuon = dateFormat1.format(date1);
            table1.addCell(new Phrase("Ngày mượn: " + ngayMuon, vietnameseFont));
            table1.addCell(new Phrase("Chuyên ngành: " + jTextField4.getText(), vietnameseFont));
            Date date2 = jDateChooser2.getDate();
            String hanTra = "";
            SimpleDateFormat dateFormat2 = new SimpleDateFormat("dd/MM/yyyy");
            hanTra = dateFormat2.format(date2);
            table1.addCell(new Phrase("Ngày phải trả: " + hanTra, vietnameseFont));
            table1.addCell(new Phrase("Người tạo phiếu: " + jTextField5.getText(), vietnameseFont));
            table1.addCell(new Phrase("" , vietnameseFont));

            document.add(table1);

            PdfPTable table2 = new PdfPTable(5);
            table2.setSpacingBefore(10);
            table2.setWidthPercentage(100);

            table2.addCell(new Phrase("Mã tài liệu", vietnameseFont));
            table2.addCell(new Phrase("Tên tài liệu", vietnameseFont));
            table2.addCell(new Phrase("NXB", vietnameseFont));
            table2.addCell(new Phrase("Tác giả", vietnameseFont));
            table2.addCell(new Phrase("Trạng thái", vietnameseFont));

            int rowCount = dstailieu.getRowCount();
            for (int i = 0; i < rowCount; i++) {
                for (int j = 0; j < dstailieu.getColumnCount(); j++) {
                    table2.addCell(new Phrase("" + dstailieu.getValueAt(i, j), vietnameseFont));
                }
            }

            document.add(table2);
            document.close();
            System.out.println("PDF created successfully.");
            JOptionPane.showMessageDialog(this, "Xuất File thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE); 

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void edit(){
        if(UserDAO.quyenHan.equals("Admin") || UserDAO.quyenHan.equals("Thủ thư")){
            this.jTextField2.setEditable(true);
            this.jTextField3.setEditable(true);
            this.jTextField4.setEditable(true);
            this.jTextField5.setEditable(true);
            this.jComboBox1.setEnabled(true);
            this.jDateChooser2.setEnabled(true);
            this.capNhat.setVisible(true);
            this.xoa.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Bạn không có quyền hạn!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_PhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_PhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_PhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_PhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_PhieuMuon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton capNhat;
    private javax.swing.JLabel chuyenNganh;
    private javax.swing.JTable dstailieu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lop;
    private javax.swing.JLabel maDG;
    private javax.swing.JLabel maPhieu;
    private javax.swing.JLabel ngayMuon;
    private javax.swing.JLabel ngaytra;
    private javax.swing.JLabel phieumuon;
    private javax.swing.JLabel tenDG;
    private javax.swing.JButton xoa;
    private javax.swing.JButton xuatPhieu;
    // End of variables declaration//GEN-END:variables
}
